### ISSUE TITLE
Update port references to use new Kitura default of 8080

### ISSUE THREAD

**Issue by kweinmeister** [IBM-Swift/generator-swiftserver#153]

**Comment by tunniclm** [comment]
@kweinmeister We did do an update for this already, did you find somewhere we might have missed? I think we did keep 8090 in some tests deliberately but most other places should have been updated. We may well have missed a default value here or there.

**Comment by kweinmeister** [comment]
You're right, it looks like all references left are in test. If you don't have a preference, it would be nice to change these as well (or at least to a port other than 8090) to help with tracking changing all the references in IBM-Swift.

https://github.com/IBM-Swift/generator-swiftserver/search?utf8=✓&q=8090&type=
L

**Comment by tunniclm** [comment]
Remaining changes implemented in https://github.com/IBM-Swift/generator-swiftserver/pull/167
