### ISSUE TITLE
.build-docker not in .cfignore or .gitignore file

### ISSUE THREAD

**Issue by tunniclm** [IBM-Swift/generator-swiftserver#187]
Since the docker image has changes to use `.build-docker` directory for the Swift project build within the docker image (so that it won't clash with `.build` for the host build), we need to add `.build-docker` to the following ignore files:

- [x] .cfignore
- [x] .gitignore

**Comment by tfrank64** [comment]
The folder that gets created is now called `.build-ubuntu` as seen [here](https://github.com/IBM-Swift/swift-ubuntu-docker/blob/master/utils/common-utils.sh#L31). I will update accordingly.

**Comment by tfrank64** [comment]
Created a couple PRs for the generator and kitura.io. Waiting for approval and merge.

**Comment by tfrank64** [comment]
Waiting for a generator release to merge documentation PR.

**Comment by tfrank64** [comment]
This was included in release 2.1.0
