### ISSUE TITLE
Only print out valid options for generator

### ISSUE THREAD

**Issue by tfrank64** [IBM-Swift/generator-swiftserver#189]
When you run `yo swiftserver --help` we are given multiple options, but a few of them don't work properly. We need to either fix them or remove them. For example, the `-h` option does not do anything, it just starts the generator.

Review:

- `-h`
- `--skip-cache`
- `--skip-install`

Related to #41

**Comment by ghost** [comment]
This appears to have been fixed?

<img width="790" alt="screen shot 2018-05-16 at 9 44 26 am" src="https://user-images.githubusercontent.com/38068894/40120689-d274081c-58ed-11e8-8ae0-f1aed625fcfc.png">

**Comment by christiancompton** [comment]
@ibm-jason do each of the options, particularly --skip-install, --skip-cache behave as expected?

**Comment by ghost** [comment]
**yo swiftserver --skip-install:**
https://asciinema.org/a/AEEXYaEatDpsMRwSpQmjQr0zC

**yo swiftserver --skip-cache:**
https://asciinema.org/a/35HvVTfYr1ixEndHmmGyBllPM

**Comment by ghost** [comment]
@christiancompton: Question(s):

1. How should I validate `--skip-cache` option? Is there an answer file that's generated (or something) that stores the answers to the prompted questions, and in this case that file would not be created?

2. Same question for `--skip-install`- does this mean that the dependency modules like FileKit and SwiftyRequest not built and added to the project?

**Comment by christiancompton** [comment]
@ibm-jason I am investigating - it seems that these options are really useful for Node/NPM, but it is not immediately clear how they should behave for Swift...

There are several options, documented in our README that should be added to this list, i.e. `--bluemix` .

**Comment by ghost** [comment]
@christiancompton - any updates on how each of these options (`--skip-cache` and `--skip-install`) would be useful in the Swift sense?

**Comment by christiancompton** [comment]
Closing as complete.
