### ISSUE TITLE
IBM Cloud Auto-Scaling service fails to initialize

### ISSUE THREAD

**Issue by tunniclm** [IBM-Swift/generator-swiftserver#432]
When starting an application generated with the Auto-Scaling service, it fails to initialize even if SwiftMetrics initializes correctly. See https://github.com/IBM-Swift/kitura-cli/issues/24

The problem is the recent refactor of the application changed the order in which the metrics and and Auto-Scaling service are initialized. SwiftMetrics needs to be initialized before the Auto-Scaling service.

**Comment by ianpartridge** [comment]
Fixed in https://github.com/IBM-Swift/generator-swiftserver/commit/4e909b93ee5061e7c417b20bfc4269deae742ecf

**Comment by tunniclm** [comment]
Published in `4.6.2`
