### ISSUE TITLE
 unsure which node6.x Node.js 8.x Node.js 10  version will work ? 

### ISSUE THREAD

**Issue by smartmouse** [IBM-Swift/generator-swiftserver#562]
Greetings - did not see a engine in the package.json.
For the generator-swifterver  version 4.x version 5.x , which node.js versions do you support?
What about the older generator-swiftserver@1.x?

Thanks in advance.

**Comment by christiancompton** [comment]
Hello @smartmouse - we support Node 4, 6, and 8 in the generator versions 2.5.0 and later.  Support for Node 10 will be coming soon.

Releases before 2.5.0 should work with Node 6 and 4.  I will add a note about this in our documentation.

**Comment by smartmouse** [comment]
Thank you for your prompt reply.
