### ISSUE TITLE
bluemix-simple-http-client-swift 0.9.0 doesn't support swift 5

### ISSUE THREAD

**Issue by Andrew-Lees11** [IBM-Swift/generator-swiftserver#698]
When you run the generator and choose to import from a swagger file you get the following package:
```
.package(url: "https://github.com/ibm-bluemix-mobile-services/bluemix-simple-http-client-swift.git", .upToNextMinor(from: "0.9.0")),
```
This then fails to resolve because bluemix-simple-http-client-swift 0.9.0 doesn't support Swift 5. Support was added in version 1.0.0 so if you update the generated version the package can then resolve.

**Comment by christiancompton** [comment]
The SDKgeneration capability stems from an internal microservice, not an external generator.  I have updated the dependency in the microservice, and will close this once I have verified that the SDKgeneration tests pass in production.

**Comment by christiancompton** [comment]
This now works in production, but it does produce warnings.  I will work on addressing this now, but will close as complete.

Clean Builds:
https://travis-ci.org/IBM-Swift/generator-swiftserver/builds/531869897
